### ISSUE TITLE
V2.0.0 not available on pkg.go.dev

### ISSUE THREAD

**Issue by rafabulsing** [sivukhin/godjot#25]
Just as it says on the title. Latest version visible on pkg.go.dev is 1.0.6.

https://pkg.go.dev/github.com/sivukhin/godjot@v1.0.6?tab=versions

**Comment by rafabulsing** [comment]
I'm guessing this PR fixes that? #24

**Comment by sivukhin** [comment]
Yes. Sorry for that inconvenience. I merged PR from @xxxserxxx and now v2 should be available. Can you check?
(btw, do you use godjot for some projects? will be keen to know any details about use cases :-) )

**Comment by rafabulsing** [comment]
No need to apologize at all. Seems like [go handles v2 releases a bit differently](https://go.dev/blog/v2-go-modules), so some confusion is to be expected.

Unfortunately, it still doesn't seems to be working for me. The [version list on pkg.go.dev](https://pkg.go.dev/github.com/sivukhin/godjot?tab=versions) still only goes up to 1.0.6. And running `go get github.com/sivukhin/godjot/v2@latest` fails with the error:

`go: module github.com/sivukhin/godjot@latest found (v1.0.6), but does not contain package github.com/sivukhin/godjot/v2`

From the cursory look I gave that PR, and what the post I linked above says, I can't really tell what's missing that is making this not work. Will try to dig deeper later on.

As for your question, I'm making a static site generator for my blog. It's nothing too fancy, I'm trying to keep it as simple as possible while still doing what I need it to. But I'll try and get it nice and clean enough to share.

Thank you for your work with this library, by the way! :)

**Comment by rafabulsing** [comment]
Ooh, I posted this and immediately had an idea for a possible cause of the problem:

I believe pkg.go.dev takes the versions through the tagged releases of the repo. Since 2.0.0 was published before that PR was closed, the tag still points to a version of the codebase which has the old module paths. So I'm guessing either the tag should be moved to the latest commit, or a new 2.0.1 release should be created pointing to that updated code.

While a new release is the most proper solution, there would be a "gap" in that 2.0.0 would never be available on pkg.go.dev. If that bothers you at all, moving the tag would solve that. And I believe by definition it would not really negatively impact anyone, even if it's not "proper", since the whole problem is that we have been unable to get the 2.0.0 release anyway.

**Comment by xxxserxxx** [comment]
With Go modules, you have to do two things past v1:

- Update the go.mod (and any import paths in your code) to point to the new path
- Tag or branch the version _that has the updated `go.mod`._

The current issue is that you have a v2.0.0 tag, but it's pointing at an old version **before** the `go.mod` change; in other words, if you clone and `git checkout v2.0.0` you get the go.mod with the wrong path.

To fix this, you need to create a new tag v2.0.1 pointing at a version with the changed `go.mod`. `pkg.go.dev` complicates this because once versions are published, they're cached by `pkg.go.dev` and it's not really possible to change them. I find this frustrating, but it makes sense: according to go modules, tagged versions should be immutable because if the tag can float it can break other software that is pointing at a specific tag. There is a way around this: bypass `pkg.go.dev`, but that only works for the individual and will still break any other projects that aren't bypassing `pkg.go.dev`, which is most.

So: to address this, just create a new `v2.0.1` tag on HEAD. We should consider `v2.0.0` unusable. This will probably not be an issue, since most folks tend to use `@latest`, but you could also make a note in the README. I, personally, don't care; I know what's going on. 

This occasionally bites me in other projects: once you push a tag on a Go project, you just have to live with it, because of `pkg.go.dev`. If it's broken, all you can do is push a new tag. 

> btw, do you use godjot for some projects? will be keen to know any details about use cases :-) 

I do! [tjot](https://hg.sr.ht/~ser/tjot), a terminal djot renderer.

I've also asked [Hugo](https://gohugo.io) and [Sourcehut](https://sr.ht) whether they'd accept patches to add support for djot, for which I would have used godjot; Hugo said "no", and Sourcehut answered that there's a standing policy that they won't add support for markup formats other than Markdown.

I can't do anything about Sourcehut (well, I _could_, but I'm not going to self-host Sourcehut), but I'm actively looking for an alternative static site generator that can support djot. Since Hugo is open source, I may also just fork it and maintain a fork that has djot support. I've gotten a couple of responses from people who saw my Hugo post and asked what the response was.

**Comment by jphastings** [comment]
Hey @sivukhin, I'd love to use `godjot` v2, but I don't believe any of us can install it until v2.0.1 is released — if you have the time it'd be very helpful! 😊

**Comment by jphastings** [comment]
@xxxserxxx for what it's worth, I'd love to see Djot support in Hugo too. Let me know if my expressing that anywhere might help with adoption!

**Comment by xxxserxxx** [comment]
> for what it's worth, I'd love to see Djot support in Hugo too.

The Hugo team has said they will not be adding other source formats. My solution was to provide a patch to another static site generator project (gozer), which was accepted. But then, of course, I made a bunch of other changes which resulted in [a fork](https://git.sr.ht/~ser/gozer) with several additional features and some philosophical changes to site source assumptions. [My personal site](https://ser1.net) is built entirely from djot sources, my fork of Gozer, and a Tufte theme ported from Hugo which is entirely JS-less and yet interactive (via CSS).
